<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>MC_Helper</AssemblyName>
    <StartupObject>MC_Helper.App</StartupObject>
    <Product>MC_Helper</Product>
    <Company>aihaoDIYlove (Personal)</Company>
    <Copyright>Copyright (c) 2026 aihaoDIYlove</Copyright>
    <Description>Minecraft 多功能辅助工具</Description>
    <Version>2.1.0</Version>
    <ApplicationIcon>img.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
